---
- name: List files in a directory
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Create directory
      file:
        path: "/var/backup/config"
        state: directory
        mode: "0777"

    - name: List files
      find:
        paths: "/var/backup/config"
        file_type: file
      register: files_list

    - name: Display files
      debug:
        var: files_list.files
