---
- name: List files in a directory
  hosts: localhost
  gather_facts: no

  tasks:
    - name: List files
      find:
        paths: "/var/backup"
        file_type: file
      register: files_list

    - name: Display files
      debug:
        var: files_list.files
